# Generated by Django 4.1.7 on 2023-05-02 11:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='time_post',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 2, 11, 41, 25, 535224, tzinfo=datetime.timezone.utc)),
        ),
    ]
